### ISSUE TITLE
名前空間とフォルダ構成は原則あわせる

### ISSUE THREAD

**Issue by ushibutatory** [Ajishiaimi/Study#15]
https://github.com/Ajishiaimi/Study/blob/master/App_Code/FB_Const.vb

> Namespace FizzBuzz_Const

名前空間を定義した場合は、原則、その階層どおりにフォルダを作成した方がよいです。

**Comment by Ajishiaimi** [comment]
@ushibutatory　テスト！

**Comment by ushibutatory** [comment]
@Ajishiaimi 通知来ました

**Comment by ushibutatory** [comment]
少しややこしいのですが、以下のようにルール化するといいと思います。
- 名前空間（namespace）→フォルダ階層
- クラス（class）→ファイル

#10 で私が挙げた例が検討不足だったせいで混乱させてしまいました。すみません。

<pre>
Namespace FizzBuzzConst
    Public MustInherit Class Values
    Public MustInherit Class Text
    Public MustInherit Class Tag
</pre>

上記の構成なら、フォルダ・ファイルは以下のような配置にした方がいい気がします。

<pre>
App_Code
└FizzBuzzConst
　├Values.vb
　├Text.vb
　└Tag.vb
</pre>

こうしてみると、少し微妙かな、と今思いました。本当申し訳ない。

おそらく、以下のようにする方がスッキリする気がします。
- フォルダ構成
  <pre>
  App_Code
  └FizzBuzzConst.vb
  </pre>
- FizzBuzzConst.vbの中身
  <pre>
  ' Namespace は定義しない
  Public MustInherit Class FizzBuzzConst
  　　Public MustInherit Class Values
  　　Public MustInherit Class Text
  　　Public MustInherit Class Tag
  </pre>
