### ISSUE TITLE
繰り返し出力はRepeaterコントロールを使ってみては？

### ISSUE THREAD

**Issue by ushibutatory** [Ajishiaimi/Study#16]
https://github.com/Ajishiaimi/Study/blob/master/FizzBuzz.aspx#L47
https://github.com/Ajishiaimi/Study/blob/master/FizzBuzz.aspx.vb#L43

今のつくりだと、結果を文字列結合して1つのラベルとして出力してますが、
せっかくASP.NETで作ったのなら、Repeaterコントロールなどを使ってみてはいかがでしょうか。

余談）個人的にはGridViewとかよりRepeaterの方が万能感があって好きです。

**Comment by ushibutatory** [comment]
https://github.com/Ajishiaimi/Study/blob/master/FizzBuzz_Repeter%E6%9C%89.aspx#L48

<pre>
Text='<%# DataBinder.Eval(Container.DataItem, "NumberOutput") %>'</td>
</pre>

`DataBinder`でも動きますが、複雑な出力処理に対応するためには
基本的には`ItemDataBound`イベントを使って実装する習慣をつけた方がよいと思います。
（例えば、数値によって行のスタイルを変える、などは`DataBinder`では対応できない。）

https://msdn.microsoft.com/ja-jp/library/system.web.ui.webcontrols.repeater.itemdatabound%28v=vs.110%29.aspx?cs-save-lang=1&cs-lang=vb#code-snippet-3

**Comment by Ajishiaimi** [comment]
@ushibutatory aspタグのtextに値を指定するのでなく、ItemDataBoundのイベントの際に出力したほうがいいということは理解できました。
実際に参考のソースを拝見しましたが、ItemDataBoundの際にうまく値を取得することができず苦戦しています。どうやったら値が取得できるのかヒントをいただけたら幸いです。

**Comment by ushibutatory** [comment]
@Ajishiaimi `DataSource`に設定したデータが`ItemDataBound`の`RepeaterItemEventArgs`に渡されます。
例えば`List(Of String)`を設定すれば、ItemDataBound内では`String`が取れる、という感じ。

<pre>
Me.rptSample.DataSource = ... ' List(Of String)
Me.rptSample.DataBind()
</pre>

↓

<pre>
Protected Sub rptSample_ItemDataBound(sender As Object, e As RepeaterItemEventArgs)
  Select Case e.Item.ItemType
    Case ListItemType.Item, ListItemType.AlternatingItem
      ' あとは以下を組み合わせれば出来るかと
      ' DirectCast(e.Item.DataItem, String) ' ←Stringが入っているのでキャストして取得
      ' DirectCast(e.Item.FindControl("lblSample"), Label) ' ←ItemTemplate内のコントロールを検索してキャスト
</pre>

伝わるかしら。

**Comment by ushibutatory** [comment]
`String`はただの例です。今回なら、`Holder`？ `ResultClass`？　を使えばいいのかな、と。

**Comment by ushibutatory** [comment]
ItemDataBoundイベント内でブレークしてウォッチ式で'e.Item'の中身を見てみると面白いと思います。
