### ISSUE TITLE
加算代入演算子を使う

### ISSUE THREAD

**Issue by ushibutatory** [Ajishiaimi/Study#17]
https://github.com/Ajishiaimi/Study/blob/master/FizzBuzz.aspx.vb#L34

以下のように書いた方がスッキリすると思います。

`Bit = Bit + 2 ^ 1`
↓
`Bit += 2 ^ 1`

**Comment by Ajishiaimi** [comment]
@ushibutatory 対応しました。

**Comment by ushibutatory** [comment]
確認しました
